### ISSUE TITLE
after viewing .js file via github raw and navigating back to non-raw. Page is malformed

### ISSUE THREAD

**Issue by Harrald** [rbudiharso/javascript-view#1]
Example: 

Looks ok:
https://github.com/DimitarChristoff/doctor/blob/master/doctor.js

Raw js gets beautified:
https://raw.github.com/DimitarChristoff/doctor/master/doctor.js

Malformed:
https://github.com/DimitarChristoff/doctor/blob/master/doctor.js

But when you go to a page without .js like:
https://github.com/DimitarChristoff/doctor/

And then go back to the .js page. The page is displayed as normal:
https://github.com/DimitarChristoff/doctor/blob/master/doctor.js

**Comment by rbudiharso** [comment]
I've fixed this issue, the addon is still waiting to be reviewed, it shouldn't take long to be approved, but if you're impatient you can install directly from [the repo](https://github.com/rahmat-budiharso/javascript-view)

In the mean time I'll close this issue :)
